/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DisconnectedRouteImport } from './routes/disconnected'
import { Route as MetersRouteImport } from './routes/meters'
import { Route as SettingsRouteImport } from './routes/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DisconnectedRoute = DisconnectedRouteImport.update({
  id: '/disconnected',
  path: '/disconnected',
  getParentRoute: () => rootRouteImport,
} as any)
const MetersRoute = MetersRouteImport.update({
  id: '/meters',
  path: '/meters',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/disconnected': typeof DisconnectedRoute
  '/meters': typeof MetersRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/disconnected': typeof DisconnectedRoute
  '/meters': typeof MetersRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/disconnected': typeof DisconnectedRoute
  '/meters': typeof MetersRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/disconnected' | '/meters' | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/disconnected' | '/meters' | '/settings'
  id: '__root__' | '/' | '/disconnected' | '/meters' | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DisconnectedRoute: typeof DisconnectedRoute
  MetersRoute: typeof MetersRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disconnected': {
      id: '/disconnected'
      path: '/disconnected'
      fullPath: '/disconnected'
      preLoaderRoute: typeof DisconnectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meters': {
      id: '/meters'
      path: '/meters'
      fullPath: '/meters'
      preLoaderRoute: typeof MetersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DisconnectedRoute: DisconnectedRoute,
  MetersRoute: MetersRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
